# Generated by Django 4.1.7 on 2023-04-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCenterMaster',
            fields=[
                ('MedicalCenterCode', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('MedicalCenterName', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('MedicalCenterTypeCode', models.IntegerField(blank=True, default='', null=True)),
                ('Status', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('UserCode', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(blank=True, default='', max_length=100)),
                ('FullName', models.CharField(blank=True, default='', max_length=50)),
                ('ContactNo', models.CharField(blank=True, default='', max_length=20)),
                ('EmailId', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('UserPass', models.CharField(blank=True, max_length=100, null=True)),
                ('UserType', models.CharField(blank=True, default='', max_length=50)),
                ('Status', models.CharField(default='A', max_length=1)),
            ],
        ),
    ]
